LibraryInfrastructure/Controllers/PublishersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryDomain.Model;
using LibraryInfrastructure.Services;

namespace LibraryInfrastructure.Controllers
{
    public class PublishersController : Controller
    {
        private readonly LibraryContext _context;

        private readonly PublisherDataPortServiceFactory _publisherDataPortServiceFactory;

        public PublishersController(LibraryContext context)
        {
            _context = context;
            _publisherDataPortServiceFactory = new PublisherDataPortServiceFactory(_context);
        }

        // GET: Publishers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Publishers.ToListAsync());
        }
        public async Task<IActionResult> Index_Admin()
        {
            return View(await _context.Publishers.ToListAsync());
        }
        public async Task<IActionResult> Index_User()
        {
            return View(await _context.Publishers.ToListAsync());
        }

        // GET: Publishers/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", "Books", new { id = publisher.Id, name = publisher.PublisherName, type = "publishers" });
        }

        public async Task<IActionResult> Details_Admin(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index_Admin", "Books", new { id = publisher.Id, name = publisher.PublisherName, type = "publishers" });
        }
        public async Task<IActionResult> Details_User(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index_User", "Books", new { id = publisher.Id, name = publisher.PublisherName, type = "publishers" });
        }

        // GET: Publishers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Publishers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Country,PublisherName,Id")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(publisher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Publishers/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers.FindAsync(id);
            if (publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }

        // POST: Publishers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Country,PublisherName,Id")] Publisher publisher)
        {
            if (id != publisher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(publisher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PublisherExists(publisher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }
        [HttpGet]
        public IActionResult Import()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile fileExcel, CancellationToken cancellationToken = default)
        {
            var importService = _publisherDataPortServiceFactory.GetImportService(fileExcel.ContentType);

            using var stream = fileExcel.OpenReadStream();

            await importService.ImportFromStreamAsync(stream, cancellationToken);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Export([FromQuery] string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    CancellationToken cancellationToken = default)
        {
            var exportService = _publisherDataPortServiceFactory.GetExportService(contentType);

            var memoryStream = new MemoryStream();

            await exportService.WriteToAsync(memoryStream, cancellationToken);

            await memoryStream.FlushAsync(cancellationToken);
            memoryStream.Position = 0;


            return new FileStreamResult(memoryStream, contentType)
            {
                FileDownloadName = $"categories_{DateTime.UtcNow.ToShortDateString()}.xlsx"
            };
        }
        [HttpGet]
        public async Task<IActionResult> ExportDocx(CancellationToken cancellationToken)
        {
            var contentType = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
            var exportService = _publisherDataPortServiceFactory.GetExportService(contentType);

            var memoryStream = new MemoryStream(); // don't use `using` here

            await exportService.WriteToAsync(memoryStream, cancellationToken);

            memoryStream.Position = 0; // reset for reading

            return new FileStreamResult(memoryStream, contentType)
            {
                FileDownloadName = $"publishers_{DateTime.UtcNow:yyyy-MM-dd}.docx"
            };
        }


        // GET: Publishers/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publishers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // POST: Publishers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var publisher = await _context.Publishers.FindAsync(id);

            if (publisher != null)
            {
                var books = _context.Books.Where(b => b.PublisherId == id).ToList();

                foreach (var book in books)
                {
                    var bookAuthors = _context.BookAuthors.Where(ba => ba.BookId == book.Id);
                    _context.BookAuthors.RemoveRange(bookAuthors);
                    var bookGenres = _context.BookGenres.Where(bg => bg.BookId == book.Id);
                    _context.BookGenres.RemoveRange(bookGenres);
                    var shelfBooks = _context.ShelfBooks.Where(sb => sb.BookId == book.Id);
                    _context.ShelfBooks.RemoveRange(shelfBooks);
                    _context.Books.Remove(book);
                }
                _context.Publishers.Remove(publisher);

                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }


        private bool PublisherExists(long id)
        {
            return _context.Publishers.Any(e => e.Id == id);
        }
    }
}

LibraryInfrastructure/Views/Publishers/Create.cshtml
@model LibraryDomain.Model.Publisher

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Publisher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublisherName" class="control-label"></label>
                <input asp-for="PublisherName" class="form-control" />
                <span asp-validation-for="PublisherName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index_Admin" class="btn btn-info">View all publishers</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

LibraryInfrastructure/Views/Publishers/Delete.cshtml
@model LibraryDomain.Model.Publisher

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Publisher</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublisherName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublisherName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index_Admin" class="btn btn-info">Back to List</a>
    </form>
</div>

LibraryInfrastructure/Views/Publishers/Details.cshtml
@model LibraryDomain.Model.Publisher

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Publisher</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublisherName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublisherName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index" class="btn btn-info">Back to List</a>
</div>

LibraryInfrastructure/Views/Publishers/Details_Admin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

LibraryInfrastructure/Views/Publishers/Details_User.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

LibraryInfrastructure/Views/Publishers/Edit.cshtml
@model LibraryDomain.Model.Publisher

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Publisher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublisherName" class="control-label"></label>
                <input asp-for="PublisherName" class="form-control" />
                <span asp-validation-for="PublisherName" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-info">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

LibraryInfrastructure/Views/Publishers/Import.cshtml
@model LibraryDomain.Model.Publisher

@{
    ViewData["Title"] = "Імпорт книг за видавництвами";
}

<h1>Імпорт</h1>
<div>
    <h3>Оберіть excel-файл для завантаження</h3>
    @using (Html.BeginForm("Import", "Publishers", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
    {
        <div>
            Завантажте Excel-файл:
            <input type="file" name="fileExcel" id="fileExcel" />
            <div>
                <input type="submit" value="Завантажити" />
            </div>
        </div>
    }
</div>

LibraryInfrastructure/Views/Publishers/Index.cshtml
@model IEnumerable<LibraryDomain.Model.Publisher>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublisherName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Country)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublisherName)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<a class="btn btn-primary mb-3" type="=submit" asp-area="" asp-controller="Publishers" asp-action="Import">Завантажити з файлу</a>
<a class="btn btn-primary mb-3" type="=submit" asp-area="" asp-controller="Publishers" asp-action="Export">Експортувати у excel файл</a>
<a class="btn btn-primary mb-3" type="=submit" asp-area="" asp-controller="Publishers" asp-action="ExportDocx">Експортувати у .docx файл</a>

LibraryInfrastructure/Views/Publishers/Index_Admin.cshtml
<h1>Видавці</h1>
<a asp-action="Create" class="btn btn-sm btn-outline-info me-1" title="Create">
    Add New Publisher
</a>
<br />
<br />
<div class="list-group">
    @foreach (var item in Model)
    {
        <div class="list-group-item d-flex justify-content-between align-items-center">
            <div>
                <h5 class="mb-1">@item.PublisherName</h5>
                <small class="text-muted">@item.Country</small>
            </div>
            <div>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-warning me-1" title="Edit">
                    <i class="bi bi-pencil-square"></i>
                </a>
                <a asp-action="Details_Admin" asp-route-id="@item.Id" class="btn btn-sm btn-outline-info me-1" title="Details">
                    <i class="bi bi-info-circle"></i>
                </a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-danger" title="Delete">
                    <i class="bi bi-trash"></i>
                </a>
            </div>
        </div>
    }
</div>
<a class="btn btn-primary mb-3" type="=submit" asp-area="" asp-controller="Publishers" asp-action="Import">Завантажити з файлу</a>
<a class="btn btn-primary mb-3" type="=submit" asp-area="" asp-controller="Publishers" asp-action="Export">Експортувати у excel файл</a>
<a class="btn btn-primary mb-3" type="=submit" asp-area="" asp-controller="Publishers" asp-action="ExportDocx">Експортувати у .docx файл</a>

LibraryInfrastructure/Views/Publishers/Index_User.cshtml
<h1>Видавці</h1>

<div class="list-group">
    @foreach (var item in Model)
    {
        <div class="list-group-item d-flex justify-content-between align-items-center">
            <div>
                <h5 class="mb-1">@item.PublisherName</h5>
                <small class="text-muted">@item.Country</small>
            </div>
            <div>
                
                <a asp-action="Details_User" asp-route-id="@item.Id" class="btn btn-sm btn-outline-info me-1" title="Details">
                    <i class="bi bi-info-circle"></i>
                </a>
                
            </div>
        </div>
    }
</div>
<br/>
<br />
<a class="btn btn-primary mb-3" type="=submit" asp-area="" asp-controller="Publishers" asp-action="Import">Завантажити з файлу</a>
<a class="btn btn-primary mb-3" type="=submit" asp-area="" asp-controller="Publishers" asp-action="Export">Експортувати у excel файл</a>
<a class="btn btn-primary mb-3" type="=submit" asp-area="" asp-controller="Publishers" asp-action="ExportDocx">Експортувати у .docx файл</a>