LibraryInfrastructure/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryDomain.Model;
using LibraryInfrastructure;
using Microsoft.AspNetCore.Authorization;

namespace LibraryInfrastructure.Controllers
{
    public class BooksController : Controller
    {
        private readonly LibraryContext _context;
        private readonly RabbitMqPublisher _publisher;

        public BooksController(LibraryContext context)
        {
            _context = context;
            _publisher = new RabbitMqPublisher();
        }

        // GET: Books
        public async Task<IActionResult> Index(int? id, string? name, string? type)
        {
            if (type == "publishers")
            {
                if (id == null) return RedirectToAction("Publishers", "Index");
                ViewBag.Id = id;
                ViewBag.Name = " видавництвом " + name;
                var bookByPublisher = _context.Books.Where(b => b.PublisherId == id).
                    Include(b => b.Publisher).
                    Include(b => b.BookAuthors).
                    ThenInclude(ba => ba.Author).
                    Include(b => b.BookGenres).
                    ThenInclude(g => g.Genre);
                return View(await bookByPublisher.ToListAsync());
            }
            if (type == "authors")
            {
                if (id == null) return RedirectToAction("Authors", "Index");
                ViewBag.Id = id;
                ViewBag.Name = "автором " + name;
                var bookByAuthor = _context.Books.Where(b => b.BookAuthors.Any(ba => ba.AuthorId == id))
                    .Include(b => b.Publisher)
                    .Include(b => b.BookAuthors)
                    .ThenInclude(ba => ba.Author).
                    Include(b => b.BookGenres).
                    ThenInclude(g => g.Genre);
                return View(await bookByAuthor.ToListAsync());
            }
            var bookBy = _context.Books.
                    Include(b => b.Publisher).
                    Include(b => b.BookAuthors).
                    ThenInclude(ba => ba.Author).
                    Include(b => b.BookGenres).
                    ThenInclude(g => g.Genre);
            return View(await bookBy.ToListAsync());
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index_Admin(int? id, string? name, string? type)
        {
            if (type == "publishers")
            {
                if (id == null) return RedirectToAction("Publishers", "Index_Admin");
                ViewBag.Id = id;
                ViewBag.Name = " видавництва " + name;
                var bookByPublisher = _context.Books.Where(b => b.PublisherId == id).
                    Include(b => b.Publisher).
                    Include(b => b.BookAuthors).
                    ThenInclude(ba => ba.Author).
                    Include(b => b.BookGenres).
                    ThenInclude(g => g.Genre);
                return View(await bookByPublisher.ToListAsync());
            }
            if (type == "genres")
            {
                if (id == null) return RedirectToAction("Genres", "Index_Admin");
                ViewBag.Id = id;
                ViewBag.Name = "жанру " + name;
                var bookByAuthor = _context.Books.Where(b => b.BookGenres.Any(ba => ba.GenreId == id))
                    .Include(b => b.Publisher)
                    .Include(b => b.BookAuthors)
                    .ThenInclude(ba => ba.Author).
                    Include(b => b.BookGenres).
                    ThenInclude(g => g.Genre);
                return View(await bookByAuthor.ToListAsync());
            }
            if (type == "authors")
            {
                if (id == null) return RedirectToAction("Authors", "Index_Admin");
                ViewBag.Id = id;
                ViewBag.Name = "автора " + name;
                var bookByAuthor = _context.Books.Where(b => b.BookAuthors.Any(ba => ba.AuthorId == id))
                    .Include(b => b.Publisher)
                    .Include(b => b.BookAuthors)
                    .ThenInclude(ba => ba.Author).
                    Include(b => b.BookGenres).
                    ThenInclude(g => g.Genre);
                return View(await bookByAuthor.ToListAsync());
            }
            var bookBy = _context.Books.
                    Include(b => b.Publisher).
                    Include(b => b.BookAuthors).
                    ThenInclude(ba => ba.Author).
                    Include(b => b.BookGenres).
                    ThenInclude(g => g.Genre);
            return View(await bookBy.ToListAsync());
        }


        public async Task<IActionResult> Index_User(int? id, string? name, string? type)
        {
            if (type == "publishers")
            {
                if (id == null) return RedirectToAction("Publishers", "Index_Admin");
                ViewBag.Id = id;
                ViewBag.Name = " видавництва " + name;
                var bookByPublisher = _context.Books.Where(b => b.PublisherId == id).
                    Include(b => b.Publisher).
                    Include(b => b.BookAuthors).
                    ThenInclude(ba => ba.Author).
                    Include(b => b.BookGenres).
                    ThenInclude(g => g.Genre);
                return View(await bookByPublisher.ToListAsync());
            }
            if (type == "genres")
            {
                if (id == null) return RedirectToAction("Genres", "Index_Admin");
                ViewBag.Id = id;
                ViewBag.Name = "жанру " + name;
                var bookByAuthor = _context.Books.Where(b => b.BookGenres.Any(ba => ba.GenreId == id))
                    .Include(b => b.Publisher)
                    .Include(b => b.BookAuthors)
                    .ThenInclude(ba => ba.Author).
                    Include(b => b.BookGenres).
                    ThenInclude(g => g.Genre);
                return View(await bookByAuthor.ToListAsync());
            }
            if (type == "authors")
            {
                if (id == null) return RedirectToAction("Authors", "Index_Admin");
                ViewBag.Id = id;
                ViewBag.Name = "автора " + name;
                var bookByAuthor = _context.Books.Where(b => b.BookAuthors.Any(ba => ba.AuthorId == id))
                    .Include(b => b.Publisher)
                    .Include(b => b.BookAuthors)
                    .ThenInclude(ba => ba.Author).
                    Include(b => b.BookGenres).
                    ThenInclude(g => g.Genre);
                return View(await bookByAuthor.ToListAsync());
            }
            var bookBy = _context.Books.
                    Include(b => b.Publisher).
                    Include(b => b.BookAuthors).
                    ThenInclude(ba => ba.Author).
                    Include(b => b.BookGenres).
                    ThenInclude(g => g.Genre);
            return View(await bookBy.ToListAsync());
        }

        // GET: Books/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Publisher).
                Include(b => b.BookAuthors).
                ThenInclude(ba => ba.Author).
                Include(b => b.BookGenres).
                ThenInclude(g => g.Genre).
                FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details_Admin(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Publisher).
                Include(b => b.BookAuthors).
                ThenInclude(ba => ba.Author).
                Include(b => b.BookGenres).
                ThenInclude(g => g.Genre).
                FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
        public async Task<IActionResult> Landing(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Publisher).
                Include(b => b.BookAuthors).
                ThenInclude(ba => ba.Author).
                Include(b => b.BookGenres).
                ThenInclude(g => g.Genre).
                FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
        public async Task<IActionResult> Details_User(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .Include(b => b.Publisher).
                Include(b => b.BookAuthors).
                ThenInclude(ba => ba.Author).
                Include(b => b.BookGenres).
                ThenInclude(g => g.Genre).
                FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }
        public async Task<IActionResult> Comment(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.Id == id);
            if (book == null)
            {

LibraryInfrastructure/Controllers/ReadingListsController.cs
using LibraryInfrastructure.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using LibraryDomain.Model;
using LibraryInfrastructure.Models;

namespace LibraryInfrastructure.Controllers
{
    public class ReadingListsController : Controller
    {
        private readonly LibraryContext _db;
        private readonly UserManager<User> _userManager;

        public ReadingListsController(LibraryContext db, UserManager<User> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);

            var myLists = await _db.ReadingLists
                .Where(l => l.OwnerId == userId)
                .ToListAsync();

            var publicLists = await _db.ReadingLists
                .Where(l => l.isPublic && l.OwnerId != userId).Include(l=> l.Owner)
                .ToListAsync();

            var vm = new ReadingListsIndexViewModel
            {
                MyLists = myLists,
                PublicLists = publicLists
            };
            return View(vm);
        }


        public async Task<IActionResult> Details(int id)
        {
            var list = await _db.ReadingLists
                .Include(l => l.Themes)
                    .ThenInclude(t => t.Items)
                .FirstOrDefaultAsync(l => l.Id == id);

            if (list == null)
                return NotFound();

            return View(list);
        }

        public async Task<IActionResult> Create()
        {
            var userId = _userManager.GetUserId(User);

            var existing = await _db.ReadingLists
                .FirstOrDefaultAsync(l => l.OwnerId == userId);

            if (existing != null)
                return RedirectToAction("Details", new { id = existing.Id });

            var list = new ReadingList
            {
                Title = "My Reading List",
                OwnerId = userId,
                isPublic = false
            };

            _db.ReadingLists.Add(list);
            await _db.SaveChangesAsync();

            return RedirectToAction("Details", new { id = list.Id });
        }

    }

}

LibraryInfrastructure/Controllers/UsersController.cs
using DocumentFormat.OpenXml.Spreadsheet;
using LibraryDomain.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LibraryInfrastructure.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var users = _userManager.Users.ToList(); // IQueryable<User>
            return View(users); // Passes users to Index.cshtml
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null) return NotFound();

            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            return View(user);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details_Admin(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user); 
        }
        public async Task<IActionResult> Details_User(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }
        public async Task<IActionResult> Edit_Admin(string id)
        {
            if (id == null) return NotFound();

            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            return View(user);
        }

        // POST: Users/Edit_Admin/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit_Admin(string id, User updatedUser)
        {
            if (id != updatedUser.Id) return NotFound();

            var user = await _userManager.FindByIdAsync(id);
            if (user == null) return NotFound();

            if (ModelState.IsValid)
            {
                user.FirstName = updatedUser.FirstName;
                user.LastName = updatedUser.LastName;
                user.Email = updatedUser.Email;
                user.UserName = updatedUser.UserName;
                user.Birthday = updatedUser.Birthday;

                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                    return RedirectToAction(nameof(Details_Admin), new { id = user.Id });

                foreach (var error in result.Errors)
                    ModelState.AddModelError("", error.Description);
            }

            return View(updatedUser);
        }

    }
}

LibraryInfrastructure/Controllers/WhiteBoardController.cs
using Microsoft.AspNetCore.Mvc;

namespace LibraryInfrastructure.Controllers
{
    public class WhiteboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LibraryInfrastructure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryInfrastructure</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_minthy.min.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryInfrastructure.styles.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Users" asp-action="Index">Your WebLibrary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Users" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Shelves" asp-action="Index_User">Shelves</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" id="mymain">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Your WebLibrary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LibraryInfrastructure/Views/Shared/_LayoutAdmin.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<LibraryDomain.Model.User> UserManager
@{
    string userId = null;
    if (User.Identity.IsAuthenticated)
    {
        var user = await UserManager.GetUserAsync(User);
        userId = user?.Id;
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryInfrastructure</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_minthy.min.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryInfrastructure.styles.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/7.0.5/signalr.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Users" asp-action="Index">Your WebLibrary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        @if (User.Identity.IsAuthenticated && userId != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Users" asp-action="Details_Admin" asp-route-id="@userId">Home</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Books" asp-action="Index_Admin">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Authors" asp-action="Index_Admin">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Genres" asp-action="Index_Admin">Genres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Publishers" asp-action="Index_Admin">Publishers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Shelves" asp-action="Index_Admin">Shelves</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                            {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="ReadingLists" asp-action="Index">Reading Lists</a>
                            </li>
                            }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Whiteboard" asp-action="Index">Whiteboard</a>
                        </li>
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <form method="post" asp-area="Identity" asp-page="/Account/Logout" class="d-inline">
                        <button type="submit" class="btn btn-outline-light">Logout</button>
                    </form>
                }
            </div>
        </nav>
    </header>
    <div class="container" id="mymain">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Your WebLibrary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LibraryInfrastructure/Views/Shared/_LayoutUser.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<LibraryDomain.Model.User> UserManager
@{
    string userId = null;
    if (User.Identity.IsAuthenticated)
    {
        var user = await UserManager.GetUserAsync(User);
        userId = user?.Id;
    }
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryInfrastructure</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_minthy.min.css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LibraryInfrastructure.styles.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/7.0.5/signalr.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Users" asp-action="Index">Your WebLibrary</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        @if (User.Identity.IsAuthenticated && userId != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link active" asp-area="" asp-controller="Users" asp-action="Details_User" asp-route-id="@userId">Home</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Books" asp-action="Index_User">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Authors" asp-action="Index_User">Authors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Genres" asp-action="Index_User">Genres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Publishers" asp-action="Index_User">Publishers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Shelves" asp-action="Index_User">Shelves</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="ReadingLists" asp-action="Index">Reading Lists</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Whiteboard" asp-action="Index">Whiteboard</a>
                        </li>
                    </ul>
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <form method="post" asp-area="Identity" asp-page="/Account/Logout" class="d-inline">
                        <button type="submit" class="btn btn-outline-light">Logout</button>
                    </form>
                }

            </div>
        </nav>
    </header>
    <div class="container" id="mymain">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Your WebLibrary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>